wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 25000
env_name:
  desc: null
  value: CartPole-v1
_wandb:
  desc: null
  value:
    code_path: code/wandb_sb3.py
    python_version: 3.10.5
    cli_version: 0.15.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690272799.502533
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.5
      5: 0.15.6
      8:
      - 1
      - 5
